export const categoryMap = {
  cosmetics: [
    "lipstick",
    "liquid lipstick",
    "lip liner",
    "lip gloss",
    "lip balm",
    "foundation",
    "face powder",
    "primer",
    "concealer",
    "blush",
    "highlighter",
    "eyeliner",
    "kajal",
    "mascara",
    "eyeshadow",
    "eyebrow pencil",
    "brush",
  ],
  haircare: [
    "shampoo",
    "conditioner",
    "hair oil",
    "hair serum",
    "hair mask",
    "hair color",
    "hair treatment",
    "styling gel spray",
    "others",
  ],
  skincare: [
    "face wash",
    "moisturizer",
    "cream",
    "lotion",
    "serum",
    "sunscreen",
    "toner",
    "scrub",
    "face mask",
    "petroleum jelly",
    "others",
  ],
  perfume: [
    "edt men",
    "edp men",
    "perfume men",
    "edt women",
    "edp women",
    "perfume women",
    "attar",
    "others",
  ],
  "mens-products": [
    "shirts",
    "t-shirts",
    "panjabi",
    "pants",
    "wallet",
    "belt",
    "watch",
    "others",
  ],
  food: [
    "oil & ghee",
    "honey",
    "dates",
    "spices",
    "nuts & seeds",
    "beverage",
    "rice",
    "flours & lentils",
    "certified",
    "pickle",
    "others",
  ],
  "baby-products": [
    "diapers",
    "baby wipes",
    "baby lotion",
    "baby oil",
    "baby shampoo",
    "baby soap",
    "baby powder",
    "feeding bottle",
    "baby food",
    "others",
  ],
} as const;